#if ($cors_allow_origin != "") {
	more_set_headers "Access-Control-Allow-Origin: $cors_allow_origin";
	more_set_headers "Timing-Allow-Origin: $cors_allow_origin";
	more_set_headers "Vary: Origin";
#}
