listen [::]:443 ssl;
listen 443 ssl;
listen [::]:80;
listen 80;

ssi on;
ssi_last_modified on;
ssi_types "application/json" "application/ld+json" "application/manifest+json" "application/xml" "text/css" "text/xml";
ssl_stapling off;
ssl_certificate /etc/ssl/certs/mlpcon.online.crt;
ssl_certificate_key /etc/ssl/private/mlpcon.online.key;

location / { include site-includes/mlpcon.online-proxy.conf; }
location = /ssi/block { return 204; }
more_set_headers "Onion-Location: http://$mlpcon_year.mlpconzi6a6tto74eijadqq34m33ptvhwr3txnmyeagmntauqfeerlid.onion$request_uri";
more_set_headers "Referrer-Policy: no-referrer-when-downgrade";
