listen [::]:443 ssl;
listen 443 ssl;
listen [::]:80;
listen 80;

ssi on;
ssi_last_modified on;
ssi_types "application/json" "application/ld+json" "application/manifest+json" "application/xml" "text/css" "text/xml";
ssl_stapling off;
ssl_certificate /etc/ssl/certs/mlpcon.online.crt;
ssl_certificate_key /etc/ssl/private/mlpcon.online.key;

# set up content security policy
set $csp_default "'self' *.mlpcon.online *.mlpcon.com mlpcon.online mlpcon.com";
set $csp_connect "connect-src $csp_default";
set $csp_font "font-src $csp_default fonts.gstatic.com";
set $csp_img "img-src $csp_default blob: data: 127.0.0.1:* www.gstatic.com u.smutty.horse cloudflare-ipfs.com marefair.org u.pone.rs";
set $csp_script "script-src $csp_default data: 'unsafe-inline'";
set $csp_style "style-src $csp_default 'unsafe-inline'";
more_set_headers "Content-Security-Policy: default-src $csp_default; $csp_connect; $csp_font; $csp_img; $csp_script; $csp_style";
if_modified_since before;
index index.html;
root /var/www/mlpcon.online/$mlpcon_year;
brotli off;
gzip off;

location /.well-known/wallets/ {
	alias /var/www/html/HIP-0002/iwtcits/;
	types { } default_type "text/plain; charset=utf-8";
}
location = /ssi/block { return 204; }

location ^~ /ssi/ {
	ssi_types *;
	default_type text/html;
	root /var/www/mlpcon.online/$mlpcon_year;
}
#location / { include site-includes/mlpcon.online-proxy.conf; }
more_set_headers "Onion-Location: http://$mlpcon_year.mlpconzi6a6tto74eijadqq34m33ptvhwr3txnmyeagmntauqfeerlid.onion$request_uri";
more_set_headers "Referrer-Policy: no-referrer-when-downgrade";
